spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enterprise_erp
    username: root
    password: mysql@123

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: enterprise-erp

server:
  port: 8080